name: Build
on:
  push:
    branches: [ '*' ]
    paths-ignore:
      - '**.md'
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v2

      - name: Setup Go
        id: go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16

      - name: Cache Go modules
        uses: actions/cache@v2
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-build-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-build-

      - name: Build
        run: go build -o ./bin/cast .

      - name: Test
        run: go test -race ./...
